language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: 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
 local_dir: dist
 on:
   branch: master