language: node_js
node_js:
 - "node"

cache: npm

script: npm run build

deploy:
 provider: pages
 skip_cleanup: true
 github_token: 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
 local_dir: dist
 on:
   branch: main